projects:
  raywhite:
    schema: ./src/graphql/raywhite/schema.graphql
    documents:
      - src/**/*.graphql
  anilist:
    schema: "https://graphql.anilist.co"
    documents:
      - src/**/*.anilist.gql
      - src/**/*.anilist.ts
  annict:
    schema:
      - "https://api.annict.com/graphql":
          headers:
            Authorization: "Bearer ${ANNICT_TOKEN}"
    documents:
      - src/**/*.annict.gql
      - src/**/*.annict.ts
