projects:
  raywhite:
    schema: ./src/graphql/raywhite/schema.graphql
    documents:
      - src/**/*.graphql
  anilist:
    schema: "https://graphql.anilist.co"
    documents:
      - src/**/*.anilist.gql
  annict:
    schema: "https://api.annict.com/graphql"
    documents:
      - src/**/*.annict.gql
