query GetAnimes($name: String!, $status: MediaListStatus!) {
  MediaListCollection(type: ANIME, userName: $name, status: $status) {
    lists {
      entries {
        status
        media {
          id
          idMal
        }
      }
    }
  }
}
